name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  run-test:
    name: 'Run tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Git clone'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0