name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-test:
    name: 'Run tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Git clone'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: 'Build and run tests'
        run: mvn test