name: CI with Allure Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    name: Run Tests & Publish Allure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
          cache: maven

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run TestNG tests (ignore failures)
        run: mvn test -Dmaven.test.failure.ignore=true -B
        env:
          CI: "true"
          browser: "chrome"

      - name: Generate Allure HTML report
        run: mvn allure:report -B

      - name: Upload TestNG XML reports (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: testng-reports
          path: target/surefire-reports/*.xml

      - name: Upload Allure raw results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Deploy Allure HTML report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/allure-maven-plugin
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
